name: Terraform Azure OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:

    runs-on: self-hosted

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Check Files
      shell: powershell
      run: |
        pwd
        dir
        tree /F

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Version
      run: terraform version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Show Files
      shell: powershell
      run: |
        Get-ChildItem
        Get-Content main.tf

    - name: Terraform Plan
      run: terraform plan -no-color

    - name: Terraform Apply
      run: terraform apply -auto-approve -no-color
    - name: Terraform State List
      run: terraform state list
