name: Terraform Azure RG Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  terraform:

    runs-on: self-hosted

    steps:

    # Checkout Terraform code
    - name: Checkout Code
      uses: actions/checkout@v5


    # Verify files
    - name: List Terraform Files
      shell: powershell
      run: |
        pwd
        Get-ChildItem
        Get-Content main.tf


    # Azure Login using OIDC
    - name: Azure Login
      uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    # Verify Azure Authentication
    - name: Verify Azure Login
      shell: powershell
      run: |
        az account show


    # Install Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4


    # Terraform Version
    - name: Terraform Version
      run: terraform version


    # Terraform Init
    - name: Terraform Init
      run: terraform init


    # Terraform Validate
    - name: Terraform Validate
      run: terraform validate


    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan -no-color


    # Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve -no-color


    # Verify Resource Group
    - name: Verify Resource Group
      shell: powershell
      run: |
        az group show --name rg-github-oidc-demo
